# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        :title

# Setup
title:            Col's Tech
description:      This site is the home to my random technical ramblings. The intention is to offer information and help in subjects that have stumped me or are of particular interest to me, and that may be of use to others out there, with a slant towards UNIX, Solaris and OpenSolaris.
tagline:          But what is it good for?
url:              https://lildude.co.uk
baseurl:          ""

paginate:         25

# Author
name:             "lildude"
author:           '@lildude'
timezone:         Europe/London

# Custom vars
google-site-verification: "nwLwtzSTTWphhTl4Xgvpyuz4AsISNYUCbnAfC02hSHA"

# SASS
sass:
  sass_dir:       _scss
  style:          compressed

compress_html:
  clippings:      all
  comments:       ["<!-- ", " -->"]
  endings:        all
  startings:      [html, body] # Google Webmaster tools needs the <head> tag.
  ignore:
    envs:         [test, local]
  profile:        false

kramdown:
  input:            GFM
  smart_quotes:     ["apos", "apos", "quot", "quot"]  # Don't do smart quoting by replacing like for like.

# Plugins
gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-json-feed

# Don't copy these files to the generated site
exclude: [CNAME, Gemfile, Gemfile.lock, LICENSE.md, Rakefile, README.md, README-ld.md, vendor, .gitignore, .ruby-version, .travis.yml]
