# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        :title

# Setup
title:            "@lildude"
description:      But what is it good for?
url:              https://lildude.co.uk
baseurl:          ""
lang:             en-GB
theme:            minima-dude

dns_prefetch:
  - images.weserv.nl
  - d33wubrfki0l68.cloudfront.net

# Author
name:             "lildude"
author:           '@lildude'
timezone:         Europe/London

microblog:
  username:       lildude
  site:           /ld
webmentions:      lildude.co.uk

# Custom vars
google-site-verification: "nwLwtzSTTWphhTl4Xgvpyuz4AsISNYUCbnAfC02hSHA"

# Defaults for the entire site - this ensures my notes and photos which use implied titles don't get a title in the feed
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      title: ""

twitter:
  username:       lildude
github:
  username:       lildude
  
social:
  name:           Colin Seymour
  links:
    - https://twitter.com/lildude

minima_dude:
  date_format: "%-d %b %Y"
  show_author: false

sass:
  sass_dir:       _scss
  style:          compressed


kramdown:
  input:            GFM
  smart_quotes:     ["apos", "apos", "quot", "quot"]  # Don't do smart quoting by replacing like for like.

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-loading-lazy
  - jekyll-include-cache
  - jekyll-image-cache

# Configure jekyll-feed
feed:
  path: atom.xml
  use_excerpts: false

# Don't copy these files to the generated site
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - LICENSE
  - Rakefile
  - README.md
  - vendor
  - sitespeed-result
  - script
  - .jekyll-cache
  - package.json
  - package-lock.json
  - postcss.config.js
  - tmp

# Include these else they don't take effect
include: [_headers, _redirects]

# Don't attempt to process these - ie leave as-is
keep_files:
  - assets
  - img
